=== nicosommi/bw-rest/src/BW-REST/REST/Resources/Schemas/UtilityTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.tibco.com/schemas/BW-REST/REST/Schema.xsd"
	 targetNamespace="http://www.tibco.com/schemas/BW-REST/REST/Schema.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:complexType name="contentType">
		<xs:sequence>
			<xs:element name="extension" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="contentTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="contentType" type="contentType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicosommi/bw-rest/src/BW-REST/REST/Resources/Data/contentTypes.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<contentTypes xmlns = "http://www.tibco.com/schemas/BW-REST/REST/Schema.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.tibco.com/schemas/BW-REST/REST/Schema.xsd UtilityTypes.xsd">
	<contentType>
		<extension>323</extension>
		<value>text/h323</value>
	</contentType>
	<contentType>
		<extension>*</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>acx</extension>
		<value>application/internet-property-stream</value>
	</contentType>
	<contentType>
		<extension>ai</extension>
		<value>application/postscript</value>
	</contentType>
	<contentType>
		<extension>aif</extension>
		<value>audio/x-aiff</value>
	</contentType>
	<contentType>
		<extension>aifc</extension>
		<value>audio/x-aiff</value>
	</contentType>
	<contentType>
		<extension>aiff</extension>
		<value>audio/x-aiff</value>
	</contentType>
	<contentType>
		<extension>asf</extension>
		<value>video/x-ms-asf</value>
	</contentType>
	<contentType>
		<extension>asr</extension>
		<value>video/x-ms-asf</value>
	</contentType>
	<contentType>
		<extension>asx</extension>
		<value>video/x-ms-asf</value>
	</contentType>
	<contentType>
		<extension>au</extension>
		<value>audio/basic</value>
	</contentType>
	<contentType>
		<extension>avi</extension>
		<value>video/x-msvideo</value>
	</contentType>
	<contentType>
		<extension>axs</extension>
		<value>application/olescript</value>
	</contentType>
	<contentType>
		<extension>bas</extension>
		<value>text/plain</value>
	</contentType>
	<contentType>
		<extension>bcpio</extension>
		<value>application/x-bcpio</value>
	</contentType>
	<contentType>
		<extension>bin</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>bmp</extension>
		<value>image/bmp</value>
	</contentType>
	<contentType>
		<extension>c</extension>
		<value>text/plain</value>
	</contentType>
	<contentType>
		<extension>cat</extension>
		<value>application/vnd.ms-pkiseccat</value>
	</contentType>
	<contentType>
		<extension>cdf</extension>
		<value>application/x-cdf</value>
	</contentType>
	<contentType>
		<extension>cdf</extension>
		<value>application/x-netcdf</value>
	</contentType>
	<contentType>
		<extension>cer</extension>
		<value>application/x-x509-ca-cert</value>
	</contentType>
	<contentType>
		<extension>class</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>clp</extension>
		<value>application/x-msclip</value>
	</contentType>
	<contentType>
		<extension>cmx</extension>
		<value>image/x-cmx</value>
	</contentType>
	<contentType>
		<extension>cod</extension>
		<value>image/cis-cod</value>
	</contentType>
	<contentType>
		<extension>cpio</extension>
		<value>application/x-cpio</value>
	</contentType>
	<contentType>
		<extension>crd</extension>
		<value>application/x-mscardfile</value>
	</contentType>
	<contentType>
		<extension>crl</extension>
		<value>application/pkix-crl</value>
	</contentType>
	<contentType>
		<extension>crt</extension>
		<value>application/x-x509-ca-cert</value>
	</contentType>
	<contentType>
		<extension>csh</extension>
		<value>application/x-csh</value>
	</contentType>
	<contentType>
		<extension>css</extension>
		<value>text/css</value>
	</contentType>
	<contentType>
		<extension>dcr</extension>
		<value>application/x-director</value>
	</contentType>
	<contentType>
		<extension>der</extension>
		<value>application/x-x509-ca-cert</value>
	</contentType>
	<contentType>
		<extension>dir</extension>
		<value>application/x-director</value>
	</contentType>
	<contentType>
		<extension>dll</extension>
		<value>application/x-msdownload</value>
	</contentType>
	<contentType>
		<extension>dms</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>doc</extension>
		<value>application/msword</value>
	</contentType>
	<contentType>
		<extension>dot</extension>
		<value>application/msword</value>
	</contentType>
	<contentType>
		<extension>dvi</extension>
		<value>application/x-dvi</value>
	</contentType>
	<contentType>
		<extension>dxr</extension>
		<value>application/x-director</value>
	</contentType>
	<contentType>
		<extension>eps</extension>
		<value>application/postscript</value>
	</contentType>
	<contentType>
		<extension>etx</extension>
		<value>text/x-setext</value>
	</contentType>
	<contentType>
		<extension>evy</extension>
		<value>application/envoy</value>
	</contentType>
	<contentType>
		<extension>exe</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>fif</extension>
		<value>application/fractals</value>
	</contentType>
	<contentType>
		<extension>flr</extension>
		<value>x-world/x-vrml</value>
	</contentType>
	<contentType>
		<extension>gif</extension>
		<value>image/gif</value>
	</contentType>
	<contentType>
		<extension>gtar</extension>
		<value>application/x-gtar</value>
	</contentType>
	<contentType>
		<extension>gz</extension>
		<value>application/x-gzip</value>
	</contentType>
	<contentType>
		<extension>h</extension>
		<value>text/plain</value>
	</contentType>
	<contentType>
		<extension>hdf</extension>
		<value>application/x-hdf</value>
	</contentType>
	<contentType>
		<extension>hlp</extension>
		<value>application/winhlp</value>
	</contentType>
	<contentType>
		<extension>hqx</extension>
		<value>application/mac-binhex40</value>
	</contentType>
	<contentType>
		<extension>hta</extension>
		<value>application/hta</value>
	</contentType>
	<contentType>
		<extension>htc</extension>
		<value>text/x-component</value>
	</contentType>
	<contentType>
		<extension>htm</extension>
		<value>text/html</value>
	</contentType>
	<contentType>
		<extension>html</extension>
		<value>text/html</value>
	</contentType>
	<contentType>
		<extension>htt</extension>
		<value>text/webviewhtml</value>
	</contentType>
	<contentType>
		<extension>ico</extension>
		<value>image/x-icon</value>
	</contentType>
	<contentType>
		<extension>ief</extension>
		<value>image/ief</value>
	</contentType>
	<contentType>
		<extension>iii</extension>
		<value>application/x-iphone</value>
	</contentType>
	<contentType>
		<extension>ins</extension>
		<value>application/x-internet-signup</value>
	</contentType>
	<contentType>
		<extension>isp</extension>
		<value>application/x-internet-signup</value>
	</contentType>
	<contentType>
		<extension>jfif</extension>
		<value>image/pipeg</value>
	</contentType>
	<contentType>
		<extension>jpe</extension>
		<value>image/jpeg</value>
	</contentType>
	<contentType>
		<extension>jpeg</extension>
		<value>image/jpeg</value>
	</contentType>
	<contentType>
		<extension>jpg</extension>
		<value>image/jpeg</value>
	</contentType>
	<contentType>
		<extension>js</extension>
		<value>application/x-javascript</value>
	</contentType>
	<contentType>
		<extension>latex</extension>
		<value>application/x-latex</value>
	</contentType>
	<contentType>
		<extension>lha</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>lsf</extension>
		<value>video/x-la-asf</value>
	</contentType>
	<contentType>
		<extension>lsx</extension>
		<value>video/x-la-asf</value>
	</contentType>
	<contentType>
		<extension>lzh</extension>
		<value>application/octet-stream</value>
	</contentType>
	<contentType>
		<extension>m13</extension>
		<value>application/x-msmediaview</value>
	</contentType>
	<contentType>
		<extension>m14</extension>
		<value>application/x-msmediaview</value>
	</contentType>
	<contentType>
		<extension>m3u</extension>
		<value>audio/x-mpegurl</value>
	</contentType>
	<contentType>
		<extension>man</extension>
		<value>application/x-troff-man</value>
	</contentType>
	<contentType>
		<extension>mdb</extension>
		<value>application/x-msaccess</value>
	</contentType>
	<contentType>
		<extension>me</extension>
		<value>application/x-troff-me</value>
	</contentType>
	<contentType>
		<extension>mht</extension>
		<value>message/rfc822</value>
	</contentType>
	<contentType>
		<extension>mhtml</extension>
		<value>message/rfc822</value>
	</contentType>
	<contentType>
		<extension>mid</extension>
		<value>audio/mid</value>
	</contentType>
	<contentType>
		<extension>mny</extension>
		<value>application/x-msmoney</value>
	</contentType>
	<contentType>
		<extension>mov</extension>
		<value>video/quicktime</value>
	</contentType>
	<contentType>
		<extension>movie</extension>
		<value>video/x-sgi-movie</value>
	</contentType>
	<contentType>
		<extension>mp2</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>mp3</extension>
		<value>audio/mpeg</value>
	</contentType>
	<contentType>
		<extension>mpa</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>mpe</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>mpeg</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>mpg</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>mpp</extension>
		<value>application/vnd.ms-project</value>
	</contentType>
	<contentType>
		<extension>mpv2</extension>
		<value>video/mpeg</value>
	</contentType>
	<contentType>
		<extension>ms</extension>
		<value>application/x-troff-ms</value>
	</contentType>
	<contentType>
		<extension>msg</extension>
		<value>application/vnd.ms-outlook</value>
	</contentType>
	<contentType>
		<extension>mvb</extension>
		<value>application/x-msmediaview</value>
	</contentType>
	<contentType>
		<extension>nc</extension>
