=== nicosommi/bw-rest/src/examples/base/rapid/UserManagement/UserSchemas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.tibco.com/schemas/rapid/UserManagement/Schema.xsd"
	 targetNamespace="http://www.tibco.com/schemas/rapid/UserManagement/Schema.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:complexType name="UserType">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="firstName" type="xs:string"/>
			<xs:element name="lastName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="User" type="UserType"/>
	<xs:complexType name="UsersType">
		<xs:sequence>
			<xs:element name="User" type="UserType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Users" type="UsersType"/>
</xs:schema>

=== nicosommi/bw-rest/src/examples/final/rapid/UserManagement/ExistingExampleUsers.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<Users xmlns = "http://www.tibco.com/schemas/rapid/UserManagement/Schema.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.tibco.com/schemas/rapid/UserManagement/Schema.xsd UserSchemas.xsd">
	<User>
		<id>060bc621-c8c8-4a8c-94b1-4436cfdd37b2</id>
		<firstName>john</firstName>
		<lastName>doe</lastName>
	</User>
	<User>
		<id>060bc621-c8c8-4a8c-94b1-4436cfdd37b3</id>
		<firstName>juan</firstName>
		<lastName>lopez</lastName>
	</User>
</Users>
